// Generated by https://quicktype.io

export interface Productos {
    codProducto:        number;
    nombre:             string;
    codTipoProducto:    number;
    unidadMedida:       string;
    nombreTipoProducto: string;
}
