// Generated by https://quicktype.io

export interface Requisiciones {
    codigoRequisicion:      number;
    fechaRequisicion:       string;
    codigoTipoRequisicion:  number;
    codigoOficina:          number;
    nombreOficina:          null;
    codigoArea:             number;
    nombreArea:             null;
    fechaEsperadaEntrega:   string;
    codigoRecibe:           number;
    codigoUsuarioCrea:      number;
    fechaCreacion:          string;
    observaciones:          string;
    codigoEstado:           number;
    codigoUsuarioEncargado: number;
    fechaAsignacion:        string;
    requisicionDetalle:     null;
    nombreTipoRequisicion:  string;
    nombreEncargado:        string;
}
