// Generated by https://quicktype.io

export interface TipoRequision {
    cod_Tipo_Requisicion: number;
    nombre:               string;
    tipo_Item:            number;
    nom_Tipo_Item:        string;
}
