// Generated by https://quicktype.io

export interface Usuarios {
    codusuario:        number;
    identificacion:    string;
    nombre:            string;
    direccion:         null | string;
    telefono:          null | string;
    login:             Login;
    codperfil:         number;
    fechacreacion:     string;
    codOficina:        number;
    estado:            number;
    codperfilHelpdesk: null | string;
    hdCodCliente:      null;
    email:             Email;
    codPersona:        number | null;
    codCuenta:         null | string;
}

export enum Email {
    ComunicacionesExpinnGmailCOM = "comunicaciones.expinn@gmail.com",
}

export enum Login {
    PWWiAQot5VDZR1V6PLXGLA = "pWWiAQot5VDZR1V6PLXGLA==",
}
